version: '3'

services:
  db:
    image: mysql:5.6
    container_name: db_geeoki
    volumes:
      - ./.db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: always
    env_file: ./.env
    environment: 
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DB}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    container_name: wp_geeoki
    ports:
      - "8080:80"
    restart: always
    volumes:
      - ./wordpress:/var/www/html/wp-content
    env_file: ./.env
    environment:
      WORDPRESS_DB_HOST: ${WP_DB_HOST}
      WORDPRESS_DB_USER: ${WP_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WP_DB_PASSWORD}
      WORDPRESS_DB_NAME: ${WP_DB_NAME}
volumes:
  db_data: